### ISSUE TITLE
Random crashes and errors with the same code.

### ISSUE THREAD

**Issue by DrJohannessen** [sourcesimian/uICAL#8]
Im using my ESP32 together with the Uical Library to parse an incoming HTTP Stream. The Stream is a ICS File. The ESP32 does really wierd and uncinsistent things. With the same Code uploaded i can observe those things:

It crashes and reboots (mostly, sometimes somewhere else) at the same Point of the ICS File.
Core  1 panic'ed (LoadProhibited)

The Uical Library throws an Error, that happens less often, happens arround 1/5 times.
uICAL Error: 
ParseError: Mismatch for: "VEVENT": END:VEVEN

The Uical Library throws another Error:
uICAL Error:
ParseError: Parse error, expected BEGIN: INVALID:

The ICS File itself is valid. An the Points where the Library crashes, or throws an Error is almost always a pretty normal ICS entry something like this: 
BEGIN:VEVENT
UID:8kBwE_JNdHQIMZLgdK1T-nNvCh1H@proton.me
DTSTAMP:20240402T201856Z
SUMMARY:Test
DTSTART;TZID=Europe/Amsterdam:20240407T080000
DTEND;TZID=Europe/Amsterdam:20240407T090000
SEQUENCE:0
STATUS:CONFIRMED
END:VEVENT

Also if i print out the SUMMARY of the Events, they come in big chunks. e.g. it prints out 50 summarys, then a small pause and than 50 summarys again. The Crashes or Errors seem to be at those pauses, could that be something about how the http stream and buffer works? 
Its reallly comfusing, that with the same code, and the same ICS File different things happen. I just press reset inbetween runs.

**Comment by sourcesimian** [comment]
The crash sounds like a resource limitation. Parsing ICAL on an embedded device is quite a challenge. Be sure to filter and discard all unwanted events as quickly as possible to keep memory usage low. And investigate the current size of the HTTP client buffers, and perhaps the output serial buffers too.
